language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

install:
  - cargo install wasm-pack
  - rustup component add rustfmt

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - wasm-pack build --target web --release --out-dir pkg && rm pkg/.gitignore
  - cargo fmt -- --check

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  keep_history: true
  on:
    branch: main
    rust: stable
