/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function day04_part_one(a: number, b: number, c: number): void;
export function day04_part_two(a: number, b: number, c: number): void;
export function day14_part_one(a: number, b: number, c: number): void;
export function day14_part_two(a: number, b: number, c: number): void;
export function day10_part_one(a: number, b: number, c: number): void;
export function day10_part_two(a: number, b: number, c: number): void;
export function day08_part_one(a: number, b: number, c: number): void;
export function day08_part_two(a: number, b: number, c: number): void;
export function day01_part_one(a: number, b: number, c: number): void;
export function day01_part_two(a: number, b: number, c: number): void;
export function day03_part_one(a: number, b: number, c: number): void;
export function day03_part_two(a: number, b: number, c: number): void;
export function day02_part_one(a: number, b: number, c: number): void;
export function day02_part_two(a: number, b: number, c: number): void;
export function day07_part_one(a: number, b: number, c: number): void;
export function day07_part_two(a: number, b: number, c: number): void;
export function day24_part_one(a: number, b: number, c: number): void;
export function day24_part_two(a: number, b: number, c: number): void;
export function day11_part_one(a: number, b: number, c: number): void;
export function day11_part_two(a: number, b: number, c: number): void;
export function day15_part_one(a: number, b: number, c: number): void;
export function day15_part_two(a: number, b: number, c: number): void;
export function day0325_part_one(a: number, b: number, c: number): void;
export function day16_part_two(a: number, b: number, c: number): void;
export function day17_part_one(a: number, b: number, c: number): void;
export function day17_part_two(a: number, b: number, c: number): void;
export function day18_part_one(a: number, b: number, c: number): void;
export function day18_part_two(a: number, b: number, c: number): void;
export function day19_part_one(a: number, b: number, c: number): void;
export function day19_part_two(a: number, b: number, c: number): void;
export function day20_part_one(a: number, b: number, c: number): void;
export function day20_part_two(a: number, b: number, c: number): void;
export function day21_part_one(a: number, b: number, c: number): void;
export function day21_part_two(a: number, b: number, c: number): void;
export function day22_part_one(a: number, b: number, c: number): void;
export function day22_part_two(a: number, b: number, c: number): void;
export function day23_part_one(a: number, b: number, c: number): void;
export function day23_part_two(a: number, b: number, c: number): void;
export function day16_part_one(a: number, b: number, c: number): void;
export function day25_part_two(a: number, b: number, c: number): void;
export function day06_part_one(a: number, b: number, c: number): void;
export function day06_part_two(a: number, b: number, c: number): void;
export function day12_part_one(a: number, b: number, c: number): void;
export function day12_part_two(a: number, b: number, c: number): void;
export function day05_part_one(a: number, b: number, c: number): void;
export function day05_part_two(a: number, b: number, c: number): void;
export function day09_part_one(a: number, b: number, c: number): void;
export function day09_part_two(a: number, b: number, c: number): void;
export function day13_part_one(a: number, b: number, c: number): void;
export function day13_part_two(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
